library(TwoSampleMR)
library(dplyr)
library(tidyverse)
library(forestplot)
library(MendelianRandomization)
library(openxlsx)

load("data/harm_dat.RData")
load("data/harm_dat_sf.RData")
load("data/mrradial_thyroid_CBC.RData") #generated by R/radialMR.R
load("data/mrradial_s_thyroid_CBC.RData") #generated by R/radialMRsteiger.R

##############################
#MR analyses
##############################

names(harm_dat)

snps <- harm_dat %>%
  select(exposure, outcome, SNP, effect_allele.exposure, other_allele.exposure, eaf.exposure, beta.exposure, se.exposure, pval.exposure, samplesize.exposure,
         beta.outcome, se.outcome,  pval.outcome, samplesize.outcome) %>%
  rename(effect_allele=effect_allele.exposure, other_allele=other_allele.exposure) %>%
  mutate(F.stat=round((beta.exposure*beta.exposure)/(se.exposure*se.exposure)))

res <- mr(harm_dat, method_list=c( "mr_ivw", "mr_weighted_median", "mr_egger_regression"))



mr_res <- generate_odds_ratios(res) %>%
     filter(id.outcome==17)

###########################################
#FIGURE: Pernicious anemia across TSH, TSH AITD, FT4, FT4 DIO1/DIO2, and hypothyroidism
#############################################
fig.1 <- mr_res %>%
    filter(method == "Inverse variance weighted")

fig.1 <-fig.1 %>%
    mutate(odds=sprintf("%5.2f", or)) %>%
    mutate(lci=sprintf("%5.2f", or_lci95)) %>%
    mutate(uci=sprintf("%5.2f", or_uci95)) %>%
    mutate(est.size=paste(odds, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 5,7,6,1,2,3,4,8)
id.outcome <- c(NA, 17,17,17,17,17, 17, 17, 17)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]


text.fig1<-cbind(
    c( "Exposures:", "AITD", "Hypothyroidism, overt", "Hypothyroidism, subclinical", "TSH", "FT4", "FT4, DIO1/DIO2", "FT4, DIO3OS",  "Hyperthyrodism, subclinical"),
    c(fig.1$est.size))
text.fig1[1, 2] <- "OR (95% CI)" # replace value in matrix: row, column, new value

#creating plot
pdf(file = 'PA.pdf', onefile=F)
PA<-forestplot(text.fig1,
               fn.ci_norm = fpDrawCircleCI,
               txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                              xlab=gpar(cex=0.8),
                              label=gpar(cex=0.8)),
               title="Risk of pernicious anemia",
               graph.pos = 2,
               mean=cbind(fig.1$or),
               upper =cbind(fig.1$or_uci95),
               lower= cbind(fig.1$or_lci95),
               lwd.ci = 1,
               vertices=TRUE,
               boxsize = 0.15,
               #clip=c(0.25, 2.1),
               is.summary=c(TRUE,rep(FALSE,8)),
               col = fpColors(box = "black",
                              line = "black"),
               xticks = c(0, 0.5, 1, 1.5, 2),
               zero=1,
               xlab="OR (95% CI)")
dev.off()

############################################
##MR
############################################

ivw <- subset_on_method(res,
                        single_snp_method = "Wald ratio",
                        multi_snp_method = "Inverse variance weighted"
)
wm <- subset_on_method(
    res,
    single_snp_method = "Wald ratio",
    multi_snp_method = "Weighted median"
)
egger <- subset_on_method(
    res,
    single_snp_method = "Wald ratio",
    multi_snp_method = "MR Egger"
)


#Steiger
res.steiger <- mr(harm_dat.steiger, method_list=c( "mr_ivw", "mr_weighted_median", "mr_egger_regression"))

ivw.steiger <- subset_on_method(
  res.steiger,
  single_snp_method = "Wald ratio",
  multi_snp_method = "Inverse variance weighted"
)
wm.steiger <- subset_on_method(
  res.steiger,
  single_snp_method = "Wald ratio",
  multi_snp_method = "Weighted median"
)
egger.steiger <- subset_on_method(
  res.steiger,
  single_snp_method = "Wald ratio",
  multi_snp_method = "MR Egger"
)


#HETREOGENEITY
het<-mr_heterogeneity(harm_dat)
het <- het %>%
  mutate(I2=100*(Q-Q_df)/Q) %>%
  mutate(I2=if_else(I2<0, 0, I2)) #https://www.ncbi.nlm.nih.gov/pmc/articles/PMC192859/
het <- subset(het, method=="Inverse variance weighted")

het.steiger<-mr_heterogeneity(harm_dat.steiger)
het.steiger <- het.steiger %>%
  mutate(I2=100*(Q-Q_df)/Q) %>%
  mutate(I2=if_else(I2<0, 0, I2))
het.steiger <- subset(het.steiger, method=="Inverse variance weighted")


#PLEIOTROPY
#Egger intercept
plt<-mr_pleiotropy_test(harm_dat)
plt <- plt %>%
  rename(se.egger=se, pval.egger=pval) %>%
  mutate(method="MR Egger")

plt.steiger<-mr_pleiotropy_test(harm_dat.steiger)
plt.steiger <- plt.steiger %>%
  rename(se.egger=se, pval.egger=pval) %>%
  mutate(method="MR Egger")

#Egger I2GX
i2gxf <- function(x, y) {
  list(id.exposure=y$id.exposure, id.outcome=y$id.outcome, I2GX=mr_egger(mr_input(bx=x$beta.exposure, bxse=x$se.exposure, by=x$beta.outcome, byse=x$se.outcome))@I.sq)
}

harm_egger <- harm_dat %>%
  filter(id.exposure!=4)  #id.exposure 4 is FT4 DIO3OS with 2 SNPs

I2GX <- harm_egger %>%
  group_by(id.exposure, id.outcome) %>%
  group_map(i2gxf)

df <- data.frame(matrix(unlist(I2GX), nrow=length(I2GX), byrow=T),stringsAsFactors=FALSE)
mregger.i2gx <- df %>%
  rename(id.exposure=X1, id.outcome=X2, I2gx=X3) %>%
  mutate(I2gx=100*I2gx) %>%
  mutate(method="MR Egger")

###############################################################################
#MR-PRESSO
###############################################################################
harm_presso <- harm_egger #id.exposure 4 is FT4 DIO3OS with 2 SNPs, so using same as Egger

mrpresso<-run_mr_presso(harm_presso, NbDistribution = 1800) #

df <- data.frame(matrix(unlist(mrpresso), nrow=length(mrpresso), byrow=T),stringsAsFactors=FALSE)
mr.presso <- df %>%
  rename(b=X1, se=X2, t=X3, p=X4, no_b=X5, no_se=X6, no_t=X7, no_p=X8, global.p=X9, bias.p=X10, snp.total=X11, snp.outliers=X12, snp.list=X13)

d <- ivw %>%
  mutate(snp.total=nsnp) %>%
  select(b, snp.total, exposure, outcome, id.exposure, id.outcome)

mr.presso <- merge(d, mr.presso, all.x = TRUE, all.y = TRUE)
mr.presso <- mr.presso %>%
  mutate(pval=p) %>%
  mutate(method="MR-PRESSO") %>%
  select(id.exposure, id.outcome, exposure, outcome, method, b, se, pval, no_b, no_se, global.p, bias.p, snp.total, snp.outliers, snp.list )

mr.presso[,6:14] <- lapply(mr.presso[,6:14], as.numeric)
mr.presso <- mr.presso %>%
  mutate(nsnp=snp.total-snp.outliers)

#####################################################
#MR-PRESSO, Steiger
#####################################################
harm_egger.steiger <- harm_dat.steiger %>% #id.exposure 4 is FT4 DIO3OS with 2 SNPs
   filter(id.exposure!=4)

I2GX <- harm_egger.steiger %>%
 group_by(id.exposure, id.outcome) %>%
 group_map(i2gxf)

df <- data.frame(matrix(unlist(I2GX), nrow=length(I2GX), byrow=T),stringsAsFactors=FALSE)
mreggeri2gx.steiger <- df %>%
 rename(id.exposure=X1, id.outcome=X2, I2gx=X3) %>%
 mutate(I2gx=100*I2gx) %>%
 mutate(method="MR Egger")

harm_presso.s <- harm_egger.steiger

mrpresso.steiger <- run_mr_presso(harm_presso.s, NbDistribution = 1800) #

df <- data.frame(matrix(unlist(mrpresso.steiger), nrow=length(mrpresso.steiger), byrow=T),stringsAsFactors=FALSE)
mrpresso.steiger <- df %>%
  rename(b=X1, se=X2, t=X3, p=X4, no_b=X5, no_se=X6, no_t=X7, no_p=X8, global.p=X9, bias.p=X10, snp.total=X11, snp.outliers=X12, snp.list=X13)

d <- ivw.steiger %>%
  mutate(snp.total=nsnp) %>%
  select(b, snp.total, exposure, outcome, id.exposure, id.outcome)

mrpresso.steiger <- merge(d, mrpresso.steiger, all.x = TRUE, all.y = TRUE)
mrpresso.steiger <- mrpresso.steiger %>%
  mutate(pval=p) %>%
  mutate(method="MR-PRESSO") %>%
  select(id.exposure, id.outcome, exposure, outcome, method, b, se, pval, no_b, no_se, global.p, bias.p, snp.total, snp.outliers, snp.list )

mrpresso.steiger[,6:14] <- lapply(mrpresso.steiger[,6:14], as.numeric)
mrpresso.steiger <- mrpresso.steiger %>%
  mutate(nsnp=snp.total-snp.outliers)

mrpresso.steiger  <- mrpresso.steiger %>%
  filter(!is.na(id.outcome))


#########################################################
#COMBINE ALL MR RESULTS
#########################################################
mr_res <- merge(res, plt, all.x=TRUE, all.y=TRUE)
mr_res <- merge(mr_res, mregger.i2gx, all.x=TRUE, all.y=TRUE)
mr_res <- merge(mr_res, het, all.x=TRUE, all.y=TRUE)
mr_res <- bind_rows(mr_res, mr.presso, mrradial)
mr_res <-mr_res[order(mr_res$id.exposure, mr_res$id.outcome, mr_res$method),]

mr_res <- mr_res %>%
  mutate(lci=b - 1.96 * se) %>%
  mutate(uci=b + 1.96 * se) %>%
  mutate(lci=if_else(outcome=="pernicious_anemia", exp(lci), lci)) %>%
  mutate(uci=if_else(outcome=="pernicious_anemia", exp(uci), uci)) %>%
  mutate(b=if_else(outcome=="pernicious_anemia", exp(b), b)) %>%
  rename(est=b)

names(mr_res)
mr_res <- mr_res[,c(5, 4, 3, 7, 25, 26, 9, 14, 16, 17, 10, 12, 13, 6, 23, 24)]

binary.exposure <- harm_dat %>%
  filter(units.exposure=="log odds") %>%
  mutate(r.exposure=NA)

binary.exposure$r.exposure <- get_r_from_lor(
  lor=binary.exposure$beta.exposure,
  af=binary.exposure$eaf.exposure,
  ncase=binary.exposure$ncase.exposure,
  ncontrol=binary.exposure$ncontrol.exposure,
  prevalence=binary.exposure$prevalence.exposure,
  model = "logit",
  correction = FALSE
)

binary.outcome <- harm_dat %>%
  filter(units.outcome=="log odds") %>%
  mutate(r.outcome=NA)

binary.outcome$r.outcome <- get_r_from_lor(
  lor=binary.outcome$beta.outcome,
  af=binary.outcome$eaf.outcome,
  ncase=binary.outcome$ncase.outcome,
  ncontrol=binary.outcome$ncontrol.outcome,
  prevalence=binary.outcome$prevalence.outcome,
  model = "logit",
  correction = FALSE
)

harm_dat_new <- left_join(harm_dat, binary.exposure)
harm_dat <- left_join(harm_dat_new, binary.outcome)

harm_dat <- harm_dat %>%
  mutate(pval.exposure = if_else(units.exposure=="log odds", as.numeric(NA), pval.exposure)) %>%
  mutate(pval.outcome = if_else(units.outcome=="log odds", as.numeric(NA), pval.outcome))

#I have pre-calculated r.exposure and r.outcome for binary traits (from get_r_from_lor), and deleted pval for exposure or outcome when binary
#so r2 is calculated from r for binary traits, and from pval and sample size for continuous traits: https://rdrr.io/github/MRCIEU/TwoSampleMR/src/R/steiger.R#sym-directionality_test

out <- directionality_test(harm_dat) %>%
  select(exposure, outcome, snp_r2.exposure, snp_r2.outcome, correct_causal_direction) #, steiger_pval
mr_res<- merge(out, mr_res, all.x=TRUE, all.y=TRUE)
names(mr_res)
mr_res <- mr_res[,c(1, 2, 6:19, 3:5)]

mr_res$method <- factor(mr_res$method, order = TRUE,
                        levels = c("Inverse variance weighted", "IVW, -RadialMR outliers", "MR-PRESSO", "Weighted median", "MR Egger"))

mr_res$outcome <- factor(mr_res$outcome, order = TRUE,
                          levels = c("pernicious_anemia", "RBC", "RDW", "HCT", "HGB",
                                     "MCHC", "MCH", "MCV", "Reticulocyte percentage", "Reticulocyte percentage (irn)",
                                     "Reticulocyte count", "Reticulocyte count (irn)", "Immature reticulocyte fraction", "Immature reticulocyte fraction (irn)",
                                     "Mean reticulocyte volume", "Mean reticulocyte volume (irn)",
                                     "Direct bilirubin (umol/L)", "Direct bilirubin (irn)", "Total bilirubin (umol/L)", "Total bilirubin (irn)"))

mr_res$exposure <- factor(mr_res$exposure, order = TRUE,
                          levels = c( "AITD", "hypothyroidism, overt", "SCH", "TSH_all",  "FT4_TOC", "FT4_DIO1_2",
                                      "FT4_DIO3OS", "hyperthyroidism"))


mr_res <-mr_res[order(mr_res$outcome, mr_res$exposure, mr_res$method),]
mr_res <-mr_res %>%
  filter(!is.na(outcome))%>%
  mutate(snp.outliers = if_else(is.na(snp.outliers), 0, snp.outliers))


#########################################################
#COMBINE ALL MR RESULTS, Steiger
#########################################################
mr_res.steiger <- merge(res.steiger, plt.steiger, all.x=TRUE, all.y=TRUE)
mr_res.steiger <- merge(mr_res.steiger, mreggeri2gx.steiger, all.x=TRUE, all.y=TRUE)
mr_res.steiger <- merge(mr_res.steiger, het.steiger, all.x=TRUE, all.y=TRUE)
mrpresso.steiger$b <-as.numeric(mrpresso.steiger$b)
mr_res.steiger <- bind_rows(mr_res.steiger, mrpresso.steiger, mrradial.steiger)
mr_res.steiger <- mr_res.steiger[order(mr_res.steiger$id.outcome, mr_res.steiger$id.exposure, mr_res.steiger$method),]

mr_res.steiger <- mr_res.steiger %>%
  mutate(lci=b - 1.96 * se) %>%
  mutate(uci=b + 1.96 * se) %>%
  mutate(lci=if_else(outcome=="pernicious_anemia", exp(lci), lci)) %>%
  mutate(uci=if_else(outcome=="pernicious_anemia", exp(uci), uci)) %>%
  mutate(b=if_else(outcome=="pernicious_anemia", exp(b), b)) %>%
  rename(est=b)

names(mr_res.steiger)
mr_res.steiger <- mr_res.steiger[,c(5, 4, 3, 7, 25, 26, 9, 14, 16, 17, 10, 12, 13, 6, 23, 24)]

#MR Steiger, Steiger filtered
binary.exposure <- harm_dat.steiger %>%
  filter(units.exposure=="log odds") %>%
  mutate(r.exposure=NA)

binary.exposure$r.exposure <- get_r_from_lor(
  lor=binary.exposure$beta.exposure,
  af=binary.exposure$eaf.exposure,
  ncase=binary.exposure$ncase.exposure,
  ncontrol=binary.exposure$ncontrol.exposure,
  prevalence=binary.exposure$prevalence.exposure,
  model = "logit",
  correction = FALSE
)

binary.outcome <- harm_dat.steiger %>%
  filter(units.outcome=="log odds") %>%
  mutate(r.outcome=NA)

binary.outcome$r.outcome <- get_r_from_lor(
  lor=binary.outcome$beta.outcome,
  af=binary.outcome$eaf.outcome,
  ncase=binary.outcome$ncase.outcome,
  ncontrol=binary.outcome$ncontrol.outcome,
  prevalence=binary.outcome$prevalence.outcome,
  model = "logit",
  correction = FALSE
)

harm_dat_new.steiger <- left_join(harm_dat.steiger, binary.exposure)
harm_dat.steiger <- left_join(harm_dat_new.steiger, binary.outcome)

harm_dat.steiger <- harm_dat.steiger %>%
  mutate(pval.exposure = if_else(units.exposure=="log odds", as.numeric(NA), pval.exposure)) %>%
  mutate(pval.outcome = if_else(units.outcome=="log odds", as.numeric(NA), pval.outcome))

out.steiger <- directionality_test(harm_dat.steiger) %>%
  select(exposure, outcome, snp_r2.exposure, snp_r2.outcome, correct_causal_direction) #, steiger_pval

mr_res.steiger<- merge(out.steiger, mr_res.steiger, all.x=TRUE, all.y=TRUE)
mr_res.steiger <- mr_res.steiger[,c(1, 2, 6:19, 3:5)]


mr_res.steiger$method <- factor(mr_res.steiger$method, order = TRUE,
                                levels = c("Inverse variance weighted", "IVW, -RadialMR outliers", "MR-PRESSO", "Weighted median", "MR Egger"))

mr_res.steiger$outcome <- factor(mr_res.steiger$outcome, order = TRUE,
                                 levels = c("pernicious_anemia", "RBC", "RDW", "HCT", "HGB",
                                            "MCHC", "MCH", "MCV", "Reticulocyte percentage", "Reticulocyte percentage (irn)",
                                            "Reticulocyte count", "Reticulocyte count (irn)", "Immature reticulocyte fraction", "Immature reticulocyte fraction (irn)",
                                            "Mean reticulocyte volume", "Mean reticulocyte volume (irn)",
                                            "Direct bilirubin (umol/L)", "Direct bilirubin (irn)", "Total bilirubin (umol/L)", "Total bilirubin (irn)"))

mr_res.steiger$exposure <- factor(mr_res.steiger$exposure, order = TRUE,
                                  levels = c("AITD", "hypothyroidism, overt", "SCH", "TSH_all",  "FT4_TOC", "FT4_DIO1_2",
                                              "FT4_DIO3OS", "hyperthyroidism"))

mr_res.steiger <-mr_res.steiger[order(mr_res.steiger$outcome, mr_res.steiger$exposure, mr_res.steiger$method),]
mr_res.steiger <-mr_res.steiger %>%
  filter(!is.na(outcome))

##order SNPs

snps$outcome <- factor(snps$outcome, order = TRUE,
                                 levels = c("pernicious_anemia", "RBC", "RDW", "HCT", "HGB",
                                            "MCHC", "MCH", "MCV", "Reticulocyte percentage", "Reticulocyte percentage (irn)",
                                            "Reticulocyte count", "Reticulocyte count (irn)", "Immature reticulocyte fraction", "Immature reticulocyte fraction (irn)",
                                            "Mean reticulocyte volume", "Mean reticulocyte volume (irn)",
                                            "Direct bilirubin (umol/L)", "Direct bilirubin (irn)", "Total bilirubin (umol/L)", "Total bilirubin (irn)"))

snps$exposure <- factor(snps$exposure, order = TRUE,
                        levels = c("AITD", "hypothyroidism, overt", "SCH",
                                    "hyperthyroidism", "TSH_all",  "FT4_TOC", "FT4_DIO1_2",
                                    "FT4_DIO3OS"))

snps <-snps[order(snps$outcome, snps$exposure, snps$SNP),]

load("data/reverse.RData")
load("data/snps_reverse.RData")
snps <- bind_rows(snps, snps_reverse)
snps <- snps %>%
  filter(!is.na(outcome)) %>%
  select(1:15)


#############################################
#SUPPLEMENTARY SUMMARY
#############################################
OUT <- createWorkbook() # Create a blank workbook

# Add some sheets to the workbook
addWorksheet(OUT, "S2")
addWorksheet(OUT, "S3")
addWorksheet(OUT, "S4")
addWorksheet(OUT, "S5")

# Write the data to the sheets
writeData(OUT, sheet = "S2", x = snps)
writeData(OUT, sheet = "S3", x = mr_res)
writeData(OUT, sheet = "S4", x = mr_res.steiger)
writeData(OUT, sheet = "S5", x = reverse)

# Export the file
saveWorkbook(OUT, "Supplementary_tables.xlsx", overwrite = TRUE)

###########################################
#FIGURE: Hyperthyroidism
#############################################
fig.1 <- ivw %>%
    filter(id.exposure==8) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
    mutate(beta=sprintf("%5.3f", b)) %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(lci=sprintf("%5.3f", lower)) %>%
    mutate(uci=sprintf("%5.3f", upper)) %>%
    mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 8, NA, 8,8,8,8,8,8)
id.outcome <- c(NA,  13,NA,14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)" # replace value in matrix: row, column, new value

#creating plot
pdf(file = 'Hyper.pdf', onefile=F)
Hyper<-forestplot(text.fig1,
                fn.ci_norm = fpDrawCircleCI,
                txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                               xlab=gpar(cex=0.8),
                               label=gpar(cex=0.8)),
                title="Hyperthyroidism, subclinical",
                graph.pos = 2,
                mean=cbind(fig.1$mean),
                upper =cbind(fig.1$upper),
                lower= cbind(fig.1$lower),
                lwd.ci = 1,
                vertices=TRUE,
                boxsize = 0.2,
                clip=c(-0.05, 0.05),
                is.summary=c(TRUE,rep(FALSE,8)), #,TRUE,rep(FALSE,6),TRUE,rep(FALSE,2)
                col = fpColors(box = "black",
                               line = "black"),
                xticks = c( -0.05, -0.025, 0, 0.025, 0.05),
                xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE: FT4
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==2) %>%
           filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
  mutate(beta=sprintf("%5.3f", b)) %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(lci=sprintf("%5.3f", lower)) %>%
  mutate(uci=sprintf("%5.3f", upper)) %>%
  mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 2,NA, 2,2,2,2,2,2)
id.outcome <- c(NA,  13,NA,14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(mean=b)

#generating table for forest plot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)" # replace value in matrix: row, column, new value

#creating plot
pdf(file = 'FT4.pdf', onefile=F)
FT4<-forestplot(text.fig1,
                fn.ci_norm = fpDrawCircleCI,
                txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                               xlab=gpar(cex=0.8),
                               label=gpar(cex=0.8)),
                title="FT4",
                graph.pos = 2,
                mean=cbind(fig.1$mean),
                upper =cbind(fig.1$upper),
                lower= cbind(fig.1$lower),
                lwd.ci = 1,
                vertices=TRUE,
                boxsize = 0.2,
                clip=c(-0.15, 0.15),
                is.summary=c(TRUE,rep(FALSE,8)),
                col = fpColors(box = "black",
                               line = "black"),
                xticks = c(-0.15, -0.1, -0.05,  0, 0.05, 0.1, 0.15),
                xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE: TSH_all
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==1 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
    mutate(beta=sprintf("%5.3f", b)) %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(lci=sprintf("%5.3f", lower)) %>%
    mutate(uci=sprintf("%5.3f", upper)) %>%
    mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA,  1,NA,1,1,1,1,1,1)
id.outcome <- c(NA,  13,NA,14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'TSH.pdf', onefile=F)
TSH<-forestplot(text.fig1,
                fn.ci_norm = fpDrawCircleCI,
                txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                               xlab=gpar(cex=0.8),
                               label=gpar(cex=0.8)),
                title="TSH",
                graph.pos = 2,
                mean=cbind(fig.1$mean),
                upper =cbind(fig.1$upper),
                lower= cbind(fig.1$lower),
                lwd.ci = 1,
                vertices=TRUE,
                boxsize = 0.2,
                #clip=c(-0.05, 0.05),
                is.summary=c(TRUE,rep(FALSE,8)),
                col = fpColors(box = "black",
                               line = "black"),
                xticks = c(-0.05, -0.025,  0, 0.025, 0.05),
                xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE, FT4, DIO3OS
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==4 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
    mutate(beta=sprintf("%5.3f", b)) %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(lci=sprintf("%5.3f", lower)) %>%
    mutate(uci=sprintf("%5.3f", upper)) %>%
    mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 4,NA, 4,4,4,4,4,4)
id.outcome <- c(NA, 13,NA, 14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'FT4_DIO3OS.pdf', onefile=F)
FT4_DIO3OS<-forestplot(text.fig1,
                     fn.ci_norm = fpDrawCircleCI,
                     txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                                    xlab=gpar(cex=0.8),
                                    label=gpar(cex=0.8)),
                     title="FT4 regulated by DIO3OS",
                     graph.pos = 2,
                     mean=cbind(fig.1$mean),
                     upper =cbind(fig.1$upper),
                     lower= cbind(fig.1$lower),
                     lwd.ci = 1,
                     vertices=TRUE,
                     boxsize = 0.2,
                     clip=c(-0.15, 0.15),
                     is.summary=c(TRUE,rep(FALSE,8)),
                     col = fpColors(box = "black",
                                    line = "black"),
                     xticks = c(-0.15, -0.1, -0.05,  0, 0.05, 0.1, 0.15),
                     xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE FT4 DIO1/2
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==3 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
    mutate(beta=sprintf("%5.3f", b)) %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(lci=sprintf("%5.3f", lower)) %>%
    mutate(uci=sprintf("%5.3f", upper)) %>%
    mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 3,NA, 3,3,3,3,3,3)
id.outcome <- c(NA, 13,NA, 14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'FT4_DIO.pdf', onefile=F)
FT4_DIO<-forestplot(text.fig1,
                    fn.ci_norm = fpDrawCircleCI,
                    txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                                   xlab=gpar(cex=0.8),
                                   label=gpar(cex=0.8)),
                    title="FT4 regulated by DIO1/DIO2",
                    graph.pos = 2,
                    mean=cbind(fig.1$mean),
                    upper =cbind(fig.1$upper),
                    lower= cbind(fig.1$lower),
                    lwd.ci = 1,
                    vertices=TRUE,
                    boxsize = 0.2,
                    #clip=c(-0.15, 0.15),
                    is.summary=c(TRUE,rep(FALSE,8)),
                    col = fpColors(box = "black",
                                   line = "black"),
                    xticks = c(-0.1, -0.05,  0, 0.05, 0.1),
                    xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE Overt Hypothyroidism
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==7 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
    mutate(beta=sprintf("%5.3f", b)) %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(lci=sprintf("%5.3f", lower)) %>%
    mutate(uci=sprintf("%5.3f", upper)) %>%
    mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 7,NA, 7,7,7,7,7,7)
id.outcome <- c(NA, 13,NA, 14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
    mutate(lower=b-1.96*se) %>%
    mutate(upper=b+1.96*se) %>%
    mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'Ohypo.pdf', onefile=F)
Ohypo<-forestplot(text.fig1,
                 fn.ci_norm = fpDrawCircleCI,
                 txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                                xlab=gpar(cex=0.8),
                                label=gpar(cex=0.8)),
                 title="Hypothyroidism, overt",
                 graph.pos = 2,
                 mean=cbind(fig.1$mean),
                 upper =cbind(fig.1$upper),
                 lower= cbind(fig.1$lower),
                 lwd.ci = 1,
                 vertices=TRUE,
                 boxsize = 0.2,
                 #clip=c(-0.15, 0.15),
                 is.summary=c(TRUE,rep(FALSE,8)),
                 col = fpColors(box = "black",
                                line = "black"),
                 xticks = c(-0.1, -0.05,  0, 0.05, 0.1),
                 xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE Subclinical Hypothyroidism
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==6 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
  mutate(beta=sprintf("%5.3f", b)) %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(lci=sprintf("%5.3f", lower)) %>%
  mutate(uci=sprintf("%5.3f", upper)) %>%
  mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA,  6,NA,6,6,6,6,6,6)
id.outcome <- c(NA,  13,NA,14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'SCH.pdf', onefile=F)
SCH<-forestplot(text.fig1,
                  fn.ci_norm = fpDrawCircleCI,
                  txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                                 xlab=gpar(cex=0.8),
                                 label=gpar(cex=0.8)),
                  title="Hypothyroidism, subclinical",
                  graph.pos = 2,
                  mean=cbind(fig.1$mean),
                  upper =cbind(fig.1$upper),
                  lower= cbind(fig.1$lower),
                  lwd.ci = 1,
                  vertices=TRUE,
                  boxsize = 0.2,
                  clip=c(-0.15, 0.15),
                  is.summary=c(TRUE,rep(FALSE,8)),
                  col = fpColors(box = "black",
                                 line = "black"),
                  xticks = c(-0.15, -0.1, -0.05,  0, 0.05, 0.1, 0.15),
                  xlab=expression(paste(beta, " (95% CI)")))
dev.off()

###########################################
#FIGURE AITD
#############################################
fig.1 <- ivw %>%
  filter(id.exposure==5 ) %>%
  filter(id.outcome==13 | id.outcome==14 | id.outcome==3 | id.outcome==4 | id.outcome==7 | id.outcome==6 | id.outcome==8 )

fig.1 <-fig.1 %>%
  mutate(beta=sprintf("%5.3f", b)) %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(lci=sprintf("%5.3f", lower)) %>%
  mutate(uci=sprintf("%5.3f", upper)) %>%
  mutate(est.size=paste(beta, "(",lci,",",uci,")"))

#align with table (number of rows to account for line jumps)
id.exposure <- c(NA, 5,NA, 5,5,5,5,5,5)
id.outcome <- c(NA, 13,NA, 14,3,4,7,6,8)
id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
panel.fig1 <- data.frame(id.exposure, id.outcome, id)

fig.1 <-merge(panel.fig1, fig.1, all.x = TRUE, all.y = TRUE)
fig.1 <-fig.1[order(fig.1$id),]  %>%
  mutate(lower=b-1.96*se) %>%
  mutate(upper=b+1.96*se) %>%
  mutate(mean=b)

#generating table for forestplot
text.fig1<-cbind(
  c("Outcomes:",  "Erythrocyte count", "Erythrocyte indices:","Erythrocyte distribution width","Hematocrit","Hemoglobin", "MCHC", "MCH","MCV"),
  c(fig.1$est.size))
text.fig1[1, 2] <- "\u03b2 (95% CI)"

#creating plot
pdf(file = 'AITD.pdf', onefile=F)
AITD<-forestplot(text.fig1,
                  fn.ci_norm = fpDrawCircleCI,
                  txt_gp=fpTxtGp(ticks=gpar(cex=0.8),
                                 xlab=gpar(cex=0.8),
                                 label=gpar(cex=0.8)),
                  title="Autoimmune thyroid disease",
                  graph.pos = 2,
                  mean=cbind(fig.1$mean),
                  upper =cbind(fig.1$upper),
                  lower= cbind(fig.1$lower),
                  lwd.ci = 1,
                  vertices=TRUE,
                  boxsize = 0.2,
                  #clip=c(-0.15, 0.15),
                  is.summary=c(TRUE,rep(FALSE,8)),
                  col = fpColors(box = "black",
                                 line = "black"),
                  xticks = c(-0.05, -0.025,  0, 0.025, 0.05),
                  xlab=expression(paste(beta, " (95% CI)")))
dev.off()
